# 👋 Name of this workflow (appears in GitHub Actions tab)
name: shell script

# ⚡ Trigger: This workflow runs whenever you push code to the repo
on: push  

jobs:
  Disabled:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4   # pulls your repo code to $GITHUB_WORKSPACE

      - name: List and Read file
        run: |
          echo "My first Github Actions Job"   # print a message
          ls -ltra                            # list files with details (long format, sorted by time)
          cat README.md                       # print contents of README.md

      - name: Generate ASCII Artwork
        run: .github/workflows/samplescript.sh                     # display the file to confirm it worked

      # ✅ Step 4: Just list files again to check if dragon.txt is created
      - name: List files again
        run: ls -ltra
